include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - avoid_relative_lib_imports
    - prefer_const_constructors

analyzer:
  errors:
    invalid_annotation_target: ignore
